export const items = [
    {
    id: 1,
    catagory: 'Mobiles',
    title:"Apple iPhone 14",
    imgSrc:'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
    amazonLink:'https://amzn.to/3PuckZp',
    description:'Apple iPhone 14(128GB) - Blue',
    price: '89999',
    },
    {
        id: 5,
        catagory: 'Laptops',
        title:"Xiaomi [Smartchoice] Notebook Pro",
        imgSrc:'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
        amazonLink:'https://amzn.to/3EzeQac',
        description:'Xiaomi [Smartchoice] Notebookpro',
        price: '49999',
    },
    {
        id: 7,
        catagory: 'Tablets',
        title:"Xiaomi pad 6",
        imgSrc:'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1000_.jpg',
        amazonLink:'https://amzn.to/3ZeNRdY',
        description:'Xiaomi pad 6|Qualcomm snapdragon 870| ',
        price: '29999', 
    },
    {
        id: 2,
        catagory: 'Mobiles',
        title:"Apple iPhone 11",
        imgSrc:'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
        amazonLink:'https://amzn.to/44MiYi6',
        description:'Apple iPhone 11(64GB) - white',
        price: '79999',
    },
    {
        id:6,
        catagory: 'Tablets',
        title:"Lenovo Tab P12 Pro AMOLED",
        imgSrc:'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
        amazonLink:'https://amzn.to/3Rabsdh',
        description:'Lenovo Tab P12 Pro AMOLED(12.6 inch (32cm),8 GB,256 GB, Wi-Fi Only),Strom Grey with Precision Pen 3',
        price: '19999',
    },
    {
        id: 3,
        catagory: 'Mobiles',
        title:"Apple iphone 13",
        imgSrc:'https://m.media-amazon.com/images/I/71xb2xkN5qL._SL1500_.jpg',
        amazonLink:'https://amzn.to/3r6XJtv',
        description:'Apple iPhone 13(128GB) - Blue',
        price: '69999',
    },
    {
        id: 4,
        catagory: 'Laptops',
        title:"Lenovo IdeaPad Slim  5",
        imgSrc:'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
        amazonLink:'https://amzn.to/44JsK4r', 
        description:'Lenovo IdeaPad Slim 5 Intel Core i5 12450H 14" (35.5cm)',
        price: '29999',      
    },
    {
        id: 9,
        catagory: 'Tablets',
        title:"Samsung Galaxy Tab A8",
        imgSrc:'https://m.media-amazon.com/images/I/51b9LjzmPCL._SL1080_.jpg',
        amazonLink:'https://amzn.to/3Pdsh4F',
        description:'Samsung Galaxy Tab A8 26.69cm (10.5 inch) Display, 4 GB RAM, 64 GB ROM Expandable, Wi-Fi tablet, Grey,(SM-X200NZAEINU)',
        price: '49999',  
        },
        {
            id: 8,
            catagory: 'Laptops',
            title:"HP MacBook Air Laptop",
            imgSrc:'https://m.media-amazon.com/images/I/71TPda7cwUL._SL1500_.jpg',
            amazonLink:'https://amzn.to/3r9rvhm',
            description:'Apple MacBook Air Laptop  M1 Chip, 13.3-inch/33.74 cm Retina Display',
            price: '89999',
        },
        
]